# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a02bfa982e8888254752f617e3567c72b3ca6e66b0bc67d0addba076f07da0691c6f7e77cfd76d8bdb44810b349f460231fd9f74c77d9178d1d28b3ca82c3a9

test:
  secret_key_base: 18b90431d577e522d967c62141ef921520d20248aaa665d1e7da52c8308a2278e12a9c56bbbaf2036fe1687245f4d535b0d811a2a0c83cdfa7b1a1261706c145

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

lab:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>